<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.gazbert.bxbot.trading.api.TestExchangeNetworkExceptionCreation" tests="2" skipped="0" failures="0" errors="0" timestamp="2018-01-08T20:56:03" hostname="ricebook" time="0.003">
  <properties/>
  <testcase name="testCreationOfExceptionWithCauseIsAsExpected" classname="com.gazbert.bxbot.trading.api.TestExchangeNetworkExceptionCreation" time="0.003"/>
  <testcase name="testCreationOfExceptionIsAsExpected" classname="com.gazbert.bxbot.trading.api.TestExchangeNetworkExceptionCreation" time="0.0"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
